export default [
  {
    id: 1,
    title: "Copper Water Dispenser",
    slug: "copper-water-dispenser",
    img: "/img/cowgee.webp",
    inerimgList: ["/img/cowgee.webp", "/img/cowgee.webp", "/img/cowgee.webp", "/img/cowgee.webp"],
    label: "BEST SELLERS",
    category: "brass",
    heading: "Copper Water Dispenser",
    price: "6450",
    rating: "4.5/5",
    discount: "30",
    description:
      "Since ancient times, Copper has been known for its anti-inflammatory, antibacterial and antiviral properties.",
  },
  {
    id: 2,
    title: "Brass Tawa",
    slug: "brass-tawa",
    img: "/img/cowgee.webp",
    inerimgList: ["/img/cowgee.webp", "/img/cowgee.webp", "/img/cowgee.webp"],
    label: "BEST SELLERS",
    category: "copper",
    heading: "Brass Tawa with Insulated handle",
    price: "500",
    rating: "4.5/5",
    discount: "30",
    description:
      "The versatility of P-TAL's Brass Roti Tawa transcends regions, uniting the essence of Indian cuisine.",
  },
  {
    id: 3,
    title: "Brass Saucepan",
    slug: "brass-saucepan",
    img: "/img/cowgee.webp",
    inerimgList: ["/img/cowgee.webp", "/img/cowgee.webp", "/img/cowgee.webp"],
    label: "BEST SELLERS",
    category: "brass",
    heading: "Brass Saucepan",
    price: "600",
    rating: "4.5/5",
    discount: "30",
    description:
      "Golden on the outside and shimmering silver on the inside, P-TAL's brass saucepan is the best saucepan",
  },
  {
    id: 4,
    title: "Brass Tawa",
    slug: "brass-tawa-2",
    img: "/img/cowgee.webp",
    inerimgList: ["/img/cowgee.webp", "/img/cowgee.webp", "/img/cowgee.webp"],
    label: "BEST SELLERS",
    category: "copper",
    heading: "Brass Tawa",
    price: "450",
    rating: "4.5/5",
    discount: "30",
    description:
      "Kesar (Saffron) is a natural antioxidant, which helps improve skin texture and provides relief from stress.",
  },
  {
    id: 5,
    title: "Copper Frypan",
    slug: "copper-frypan",
    category: "brass",
    img: "/img/cowgee.webp",
    inerimgList: ["/img/cowgee.webp", "/img/cowgee.webp", "/img/cowgee.webp"],
    label: "Newly launched",
    heading: "Copper Frypan",
    price: "80",
    rating: "4.5/5",
    discount: "30",
    description:
      "Whether you’re looking for a crispy half-fried egg or golden, crunchy potato cutlets, P-TAL’s copper frying pan",
  },


];
